export const QUESTION_BANK_FIELDS = {
  id: 'ID',
  year: '年度',
  category: '類科',
  subject: '科目',
  questionNumber: '題號',
  type: '題型',
  score: '分數',
  learningTheme: '類別',
  coreConcept: '核心概念',
  knowledgeNode: '核心概念',
  legacyKnowledgeNode: '知識節點',
  stem: '題幹',
  optionA: 'A',
  optionB: 'B',
  optionC: 'C',
  optionD: 'D',
  correctAnswer: '標準答案',
  myAnswer: '我的答案',
  isCorrect: '是否答對',
  stemAnalysis: '題幹分析',
  optionAAnalysis: 'A解析',
  optionBAnalysis: 'B解析',
  optionCAnalysis: 'C解析',
  optionDAnalysis: 'D解析',
  essayReferenceAnswer: '非選參考答案',
  solvingTechnique: '解題技巧',
  solvingTip: '解題技巧',
  confusingConcepts: '易混淆概念',
  commonMistake: '易混淆概念',
  familiarity: '熟悉度',
  wrongCount: '錯誤次數',
  drawn: '已抽過',
  lastReview: '最後複習',
  nextReview: '下次複習',
  sourcePage: '來源頁',
  note: '備註',
  shortcutKeywords: '捷徑關鍵字',
  coreConceptSynonyms: '核心概念同義詞',
  bonusConcepts: '加分概念',
} as const;

export const CHOICE_QUESTION_TYPE = '選擇題';
export const ESSAY_QUESTION_TYPE = '非選題';

export const QUESTION_BANK_TEMPLATE_HEADERS = [
  QUESTION_BANK_FIELDS.id,
  QUESTION_BANK_FIELDS.year,
  QUESTION_BANK_FIELDS.category,
  QUESTION_BANK_FIELDS.subject,
  QUESTION_BANK_FIELDS.questionNumber,
  QUESTION_BANK_FIELDS.type,
  QUESTION_BANK_FIELDS.score,
  QUESTION_BANK_FIELDS.learningTheme,
  QUESTION_BANK_FIELDS.coreConcept,
  QUESTION_BANK_FIELDS.stem,
  QUESTION_BANK_FIELDS.optionA,
  QUESTION_BANK_FIELDS.optionB,
  QUESTION_BANK_FIELDS.optionC,
  QUESTION_BANK_FIELDS.optionD,
  QUESTION_BANK_FIELDS.correctAnswer,
  QUESTION_BANK_FIELDS.myAnswer,
  QUESTION_BANK_FIELDS.isCorrect,
  QUESTION_BANK_FIELDS.stemAnalysis,
  QUESTION_BANK_FIELDS.optionAAnalysis,
  QUESTION_BANK_FIELDS.optionBAnalysis,
  QUESTION_BANK_FIELDS.optionCAnalysis,
  QUESTION_BANK_FIELDS.optionDAnalysis,
  QUESTION_BANK_FIELDS.essayReferenceAnswer,
  QUESTION_BANK_FIELDS.solvingTechnique,
  QUESTION_BANK_FIELDS.confusingConcepts,
  QUESTION_BANK_FIELDS.familiarity,
  QUESTION_BANK_FIELDS.wrongCount,
  QUESTION_BANK_FIELDS.drawn,
  QUESTION_BANK_FIELDS.lastReview,
  QUESTION_BANK_FIELDS.nextReview,
  QUESTION_BANK_FIELDS.sourcePage,
  QUESTION_BANK_FIELDS.note,
  QUESTION_BANK_FIELDS.shortcutKeywords,
  QUESTION_BANK_FIELDS.coreConceptSynonyms,
  QUESTION_BANK_FIELDS.bonusConcepts,
] as const;

export const REQUIRED_QUESTION_BANK_HEADERS = [
  QUESTION_BANK_FIELDS.id,
  QUESTION_BANK_FIELDS.year,
  QUESTION_BANK_FIELDS.category,
  QUESTION_BANK_FIELDS.subject,
  QUESTION_BANK_FIELDS.questionNumber,
  QUESTION_BANK_FIELDS.type,
  QUESTION_BANK_FIELDS.score,
  QUESTION_BANK_FIELDS.learningTheme,
  QUESTION_BANK_FIELDS.coreConcept,
  QUESTION_BANK_FIELDS.stem,
  QUESTION_BANK_FIELDS.correctAnswer,
] as const;

export const REQUIRED_QUESTION_VALUE_FIELDS = [QUESTION_BANK_FIELDS.stem] as const;
