export const JLS_LEARNING_RECORDS_STORAGE_KEY = 'JLS_LEARNING_RECORDS';
export const JLS_IMPORTED_QUESTION_BANK_STORAGE_KEY = 'JLS_IMPORTED_QUESTION_BANK';
export const JLS_ORPHANED_LEARNING_RECORDS_STORAGE_KEY = 'jtep.orphanedLearningRecords.v1';
